image: openjdk:11

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/

build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/

test:
  stage: test
  script:
    - gradle test
